### ISSUE TITLE
Additional White space between cron commands

### ISSUE THREAD

**Issue by JoelBeer** [bitfield/cronrun#1]
## Issue
When writing a crontab file, if you add additional spaces between the cron command lines it invalidates the file and ALL crons in that file will not run.

## Example
``` 
#This cron runs at X time 
* * * * * /var/www/site/crons
#This cron runs at Y time 
* * * * * /var/www/site/crons

ADDITIONAL LINE BREAKS

#This cron runs at Z time 
* * * * * **/var/www/site/crons**
```

## Reason for fix
As some crontab files can grow considerably, being able to visually separate different cons would be useful for navigating the file.

**Comment by bitfield** [comment]
Thanks @JoelBeer! I'll fix that.

**Comment by bitfield** [comment]
How's that for fast service @JoelBeer? 😄
